name: Publish to PyPI 📦

on:
  push:
    # tags:
    #   - "v*"

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y gettext

      - name: Install build dependencies
        run: pip3 install pretix-plugin-build twine check-manifest pip setuptools wheel build -U

      - name: Run check-manifest
        run: check-manifest .
        working-directory: .

      - name: Build package
        run: python -m build

      # - name: Publish package to PyPi
      #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
